-- CART_ID 에 INDEX가 걸려 있으면 수행시간이 이게 더 빠름
SELECT DISTINCT A.CART_ID
FROM CART_PRODUCTS A
JOIN CART_PRODUCTS B ON A.CART_ID = B.CART_ID
WHERE A.NAME = 'Milk' AND B.NAME = 'Yogurt'
ORDER BY CART_ID

/

SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Milk'
INTERSECT
SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Yogurt'
ORDER BY CART_ID
