SELECT c.CAR_ID, c.CAR_TYPE, c.daily_fee * (100 - p.discount_rate)/100 * 30 AS fee 
FROM CAR_RENTAL_COMPANY_CAR c, CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
WHERE c.CAR_TYPE(+) = p.CAR_TYPE
AND DURATION_TYPE = '30일 이상'
AND NOT EXISTS (SELECT 1
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
            WHERE TO_CHAR(END_DATE, 'YYYYMMDD') > '20221101'
            AND TO_CHAR(START_DATE, 'YYYYMMDD') < '20221130'
            AND h.CAR_ID = c.CAR_ID
) AND c.CAR_TYPE IN ('세단', 'SUV')
AND c.daily_fee * (100 - p.discount_rate)/100 * 30
BETWEEN 500000 AND 2000000
ORDER BY fee desc, CAR_TYPE ASC, CAR_ID DESC;