-- 코드를 입력하세요
# SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE),2) as SCORE 
# FROM REST_INFO A LEFT OUTER JOIN REST_REVIEW B
# on A.REST_ID = B.REST_ID
# WHERE A.ADDRESS LIKE '%서울%'
# GROUP BY A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS
# HAVING ROUND(AVG(B.REVIEW_SCORE),2)
# ORDER BY SCORE DESC, A.FAVORITES DESC;

# WHERE SUBSTR(A.TEL, 1, 2) = "02"


SELECT I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES,ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO I 
JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE '서울%' 
GROUP BY I.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC