WITH CAR AS
 (SELECT DISTINCT CAR_ID
  FROM   CAR_RENTAL_COMPANY_RENTAL_HISTORY
  WHERE  TO_DATE('20221016','YYYYMMDD') BETWEEN START_DATE AND END_DATE)
SELECT R.CAR_ID,
       CASE 
           WHEN RC.CAR_ID IS NOT NULL THEN '대여중'
           ELSE '대여 가능'
       END AS AVAILABILITY
FROM (SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) R, CAR RC
WHERE R.CAR_ID = RC.CAR_ID(+)
ORDER BY CAR_ID DESC;