SELECT o.product_id
      ,p.product_name
      ,o.TOTAL_AMOUNT * p.PRICE AS TOTAL_SALES
FROM   (SELECT PRODUCT_ID
              ,SUM(AMOUNT) AS TOTAL_AMOUNT
        FROM   FOOD_ORDER
        WHERE  TO_CHAR(PRODUCE_DATE, 'YYYYMM') = '202205'
        GROUP  BY PRODUCT_ID) o
      ,FOOD_PRODUCT p
WHERE  o.PRODUCT_ID = p.PRODUCT_ID(+)
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;