-- 코드를 작성해주세요
SElECT count(*) AS FISH_COUNT from (
    SELECT FI.ID, FI.FISH_TYPE, FNI.FISH_NAME from FISH_INFO FI LEFT JOIN
    FISH_NAME_INFO FNI on FI.FISH_TYPE = FNI.FISH_TYPE WHERE
    FNI.FISH_NAME = "BASS" OR FNI.FISH_NAME = "SNAPPER")AS FISH_DATA;