SELECT DISTINCT h.CAR_ID
FROM   CAR_RENTAL_COMPANY_RENTAL_HISTORY h
      ,CAR_RENTAL_COMPANY_CAR            c
WHERE  h.car_id = c.CAR_ID(+)
       AND TO_CHAR(h.START_DATE, 'MM') = '10'
       AND c.CAR_TYPE = '세단'
ORDER BY CAR_ID DESC;