-- 코드를 입력하세요
SELECT INFO.INGREDIENT_TYPE, SUM(half.total_order) as TOTAL_ORDER
FROM FIRST_HALF half
LEFT JOIN ICECREAM_INFO INFO
ON half.flavor = INFO.flavor
GROUP BY INFO.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC