SELECT t.TITLE, t.BOARD_ID, k.REPLY_ID, k.WRITER_ID, k.CONTENTS, 
DATE_FORMAT(k.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD t
JOIN USED_GOODS_REPLY k ON t.BOARD_ID = k.BOARD_ID
WHERE SUBSTR(t.CREATED_DATE, 1, 7) = '2022-10'
ORDER BY k.CREATED_DATE ASC, t.TITLE ASC;
